

# This file was *autogenerated* from the file testIII.sage
from sage.all_cmdline import *   # import sage library

_sage_const_81 = Integer(81); _sage_const_44 = Integer(44); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3)
import os
os.chdir('..')
load('fpMKIII.sage')
Z=BinaryQF(_sage_const_81 ,_sage_const_44 ,_sage_const_6 )
with open('data/Sp4Z.20_Ups.json', 'r') as f:
	L = json.load(f)
E = SPMF(L)
F=twistForms(E,_sage_const_3 )


